"""
Configuration for the user_home blueprint.
"""

NUM_LATEST_POSTS_TO_DISPLAY = 3
NUM_UPCOMING_EVENTS_TO_DISPLAY = 3
NUM_EVENT_HOSTING_TO_DISPLAY = 3
NUM_EVENT_ATTENDING_TO_DISPLAY = 3
MAX_NETWORKS_TO_LOAD = 50
